import os
import tempfile
from typing import Optional
from pathlib import Path

from mineru.cli.client import do_parse
from pypdf import PdfReader, PdfWriter


def _extract_pdf_page(pdf_path: str, page_num: int) -> str:
    """Extract a specific page from PDF and save to temporary file."""
    reader = PdfReader(pdf_path)
    
    # Validate page number
    if page_num < 1 or page_num > len(reader.pages):
        raise ValueError(f"Page {page_num} does not exist. PDF has {len(reader.pages)} pages.")
    
    # Create single-page PDF
    writer = PdfWriter()
    writer.add_page(reader.pages[page_num - 1])  # Convert to 0-based index
    
    # Save to temporary file
    temp_file = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    temp_file.close()
    
    with open(temp_file.name, "wb") as output_pdf:
        writer.write(output_pdf)
    
    return temp_file.name


def run_mineru_vlm_vllm_server(
    pdf_path: str, 
    page_num: int = 1, 
    server_url: str = "http://127.0.0.1:8000",
    lang: str = "en",
    verbose: bool = False
) -> str:
    """
    Convert a PDF page to markdown using MinerU's VLM with HTTP client backend.
    
    This function uses MinerU's official processing pipeline with the vlm-http-client backend,
    which connects to a running MinerU VLM server to preserve table structure and formatting properly.
    
    Args:
        pdf_path: Path to the PDF file
        page_num: Page number to process (1-indexed)
        server_url: URL of the running MinerU VLM server (e.g., "http://127.0.0.1:8000")
        lang: Document language for processing
        verbose: Enable debug output
        
    Returns:
        str: The OCR result in markdown format with preserved table structure.
        
    Raises:
        ValueError: If the page number is invalid or PDF conversion fails
        FileNotFoundError: If the PDF file doesn't exist
    """
    if not Path(pdf_path).exists():
        raise FileNotFoundError(f"PDF file not found: {pdf_path}")
    
    temp_pdf_path: Optional[str] = None
    
    try:
        # Extract specific page if needed
        if page_num > 0:
            if verbose:
                print(f"Extracting page {page_num} from PDF")
            temp_pdf_path = _extract_pdf_page(pdf_path, page_num)
            pdf_to_process = temp_pdf_path
        else:
            pdf_to_process = pdf_path
        
        # Read PDF bytes for MinerU processing
        with open(pdf_to_process, "rb") as f:
            pdf_bytes = f.read()
        
        # Create temporary output directory for MinerU processing
        with tempfile.TemporaryDirectory() as output_dir:
            if verbose:
                print(f"Using MinerU vlm-http-client backend with server: {server_url}")
                print(f"Output directory: {output_dir}")
            
            # Use MinerU's official VLM HTTP client backend
            do_parse(
                output_dir=output_dir,
                pdf_file_names=[os.path.basename(pdf_to_process)],
                pdf_bytes_list=[pdf_bytes],
                p_lang_list=[lang],  # Language setting
                backend="http-client",  # Use VLM HTTP client backend
                parse_method="auto",  # Auto-detect parsing method
                server_url=server_url,  # VLM server URL
                formula_enable=True,  # Enable formula parsing
                table_enable=True,   # Enable table parsing
                f_dump_md=True,  # Generate markdown files
                f_dump_middle_json=verbose,  # Dump intermediate JSON if verbose
                f_dump_model_output=verbose,  # Dump model output if verbose
                f_dump_orig_pdf=False,  # Don't duplicate original PDF
                f_dump_content_list=False,  # Don't dump content list
                f_draw_layout_bbox=False,  # Don't draw layout boxes
                f_draw_span_bbox=False,  # Don't draw span boxes
            )
            
            # Find and read the generated markdown file
            md_files = []
            for root, dirs, files in os.walk(output_dir):
                for file in files:
                    if file.endswith('.md') and not file.endswith('_layout.pdf') and not file.endswith('_span.pdf'):
                        md_files.append(os.path.join(root, file))
            
            if not md_files:
                raise ValueError("No markdown file generated by MinerU VLM backend")
            
            # Read the first (and likely only) markdown file
            with open(md_files[0], 'r', encoding='utf-8') as f:
                md_content = f.read()
            
            if verbose:
                print(f"Generated markdown file: {md_files[0]}")
                print(f"Generated markdown length: {len(md_content)} characters")
                if "<table>" in md_content or "|" in md_content:
                    print("Table structure detected in MinerU output ✓")
                if "\\[" in md_content or "\\(" in md_content:
                    print("LaTeX equations detected in MinerU output ✓")
            
            return md_content
    
    finally:
        # Clean up the temporary PDF file if it was created
        if temp_pdf_path and os.path.exists(temp_pdf_path):
            os.unlink(temp_pdf_path)
