import os
import tempfile

from mineru.cli.client import do_parse
from pypdf import PdfReader, PdfWriter


def run_mineru(pdf_path: str, page_num: int = 1) -> str:
    temp_file = None  # Initialize to avoid NameError in finally block

    try:
        if page_num > 0:  # If a specific page is requested
            reader = PdfReader(pdf_path)

            # Check if the requested page exists
            if page_num > len(reader.pages):
                raise ValueError(f"Page {page_num} does not exist in the PDF. PDF has {len(reader.pages)} pages.")

            # Create a new PDF with just the requested page
            writer = PdfWriter()
            # pypdf uses 0-based indexing, so subtract 1 from page_num
            writer.add_page(reader.pages[page_num - 1])

            # Save the extracted page to a temporary file
            temp_file = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
            temp_file.close()  # Close the file but keep the name

            with open(temp_file.name, "wb") as output_pdf:
                writer.write(output_pdf)

            pdf_to_process = temp_file.name
        else:
            pdf_to_process = pdf_path

        # Read the PDF file as bytes
        with open(pdf_to_process, "rb") as f:
            pdf_bytes = f.read()

        # Create temporary output directory for mineru processing
        with tempfile.TemporaryDirectory() as output_dir:
            # Use the new mineru API
            do_parse(
                output_dir=output_dir,
                pdf_file_names=[os.path.basename(pdf_to_process)],
                pdf_bytes_list=[pdf_bytes],
                p_lang_list=["en"],  # Default to English
                backend="vlm-sglang-engine",  
                parse_method="auto",  # Auto-detect parsing method
            )

            # Find and read the generated markdown file
            md_files = []
            for root, dirs, files in os.walk(output_dir):
                for file in files:
                    if file.endswith('.md'):
                        md_files.append(os.path.join(root, file))
            
            if not md_files:
                raise ValueError("No markdown file generated by mineru")
            
            # Read the first (and likely only) markdown file
            with open(md_files[0], 'r', encoding='utf-8') as f:
                md_content = f.read()

            return md_content

    finally:
        # Clean up the temporary file if it was created
        if temp_file and os.path.exists(temp_file.name):
            os.unlink(temp_file.name)