import os
import tempfile
from typing import Literal

from mineru.cli.client import do_parse
from pypdf import PdfReader, PdfWriter


def run_mineru_vlm_sglang_server(
    pdf_path: str, 
    page_num: int = 1, 
    server: str = "localhost:30000",
    lang: str = "en"
) -> str:
    """
    Convert page of a PDF file to markdown using MinerU's VLM SGLang client backend.
    
    This uses MinerU's own processing pipeline with the vlm-sglang-client backend,
    which preserves table structure and formatting properly.
    
    Args:
        pdf_path: Path to the PDF file
        page_num: Page number to process (1-indexed) 
        server: SGLang server address (e.g., "localhost:30000")
        lang: Document language for processing
        
    Returns:
        str: The OCR result in markdown format with preserved table structure.
    """
    temp_file = None  # Initialize to avoid NameError in finally block

    try:
        if page_num > 0:  # If a specific page is requested
            reader = PdfReader(pdf_path)

            # Check if the requested page exists
            if page_num > len(reader.pages):
                raise ValueError(f"Page {page_num} does not exist in the PDF. PDF has {len(reader.pages)} pages.")

            # Create a new PDF with just the requested page
            writer = PdfWriter()
            # pypdf uses 0-based indexing, so subtract 1 from page_num
            writer.add_page(reader.pages[page_num - 1])

            # Save the extracted page to a temporary file
            temp_file = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
            temp_file.close()  # Close the file but keep the name

            with open(temp_file.name, "wb") as output_pdf:
                writer.write(output_pdf)

            pdf_to_process = temp_file.name
        else:
            pdf_to_process = pdf_path

        # Read the PDF file as bytes
        with open(pdf_to_process, "rb") as f:
            pdf_bytes = f.read()

        # Create temporary output directory for mineru processing
        with tempfile.TemporaryDirectory() as output_dir:
            # Use MinerU's VLM SGLang client backend
            server_url = f"http://{server}"
            
            print(f"DEBUG: Using MinerU vlm-sglang-client backend with server: {server_url}")
            
            do_parse(
                output_dir=output_dir,
                pdf_file_names=[os.path.basename(pdf_to_process)],
                pdf_bytes_list=[pdf_bytes],
                p_lang_list=[lang],  # Language setting
                backend="vlm-sglang-client",  # Use VLM SGLang client backend
                parse_method="auto",  # Auto-detect parsing method
                server_url=server_url,  # SGLang server URL
                formula_enable=True,  # Enable formula parsing
                table_enable=True,   # Enable table parsing
            )

            # Find and read the generated markdown file
            md_files = []
            for root, dirs, files in os.walk(output_dir):
                for file in files:
                    if file.endswith('.md'):
                        md_files.append(os.path.join(root, file))
            
            if not md_files:
                raise ValueError("No markdown file generated by MinerU VLM backend")
            
            # Read the first (and likely only) markdown file
            with open(md_files[0], 'r', encoding='utf-8') as f:
                md_content = f.read()
                
            print(f"DEBUG: Generated markdown length: {len(md_content)} characters")
            if "<table>" in md_content:
                print("DEBUG: HTML tables detected in MinerU output ✓")

            return md_content

    finally:
        # Clean up the temporary file if it was created
        if temp_file and os.path.exists(temp_file.name):
            os.unlink(temp_file.name)
